"""current db

Revision ID: bb8404fe36fc
Revises: 
Create Date: 2023-03-09 05:41:35.260911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8404fe36fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('speaker_id', sa.BigInteger(), nullable=True),
    sa.Column('game_status', sa.Integer(), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['timing.id'], ),
    sa.PrimaryKeyConstraint('id', 'game_id')
    )
    op.create_table('word',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('timeout', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id', 'player_id'], ['word_player.game_id', 'word_player.id'], name='game_player'),
    sa.PrimaryKeyConstraint('id', 'time')
    )
    op.create_table('vote',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('voter_id', sa.BigInteger(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('vote_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id', 'word_time'], ['word.id', 'word.time'], name='game_word_time'),
    sa.PrimaryKeyConstraint('id', 'word_time', 'voter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('word')
    op.drop_table('word_player')
    op.drop_table('timing')
    op.drop_table('admins')
    # ### end Alembic commands ###
